version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: onfinality/subql-node:v3.0.4
    # depends_on:
    #   "postgres":
    #     condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      # - ${SUB_COMMAND} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --db-schema=avail-indexer
      - --workers=4
      - --unfinalized-blocks=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 10s
      timeout: 50s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:v2.5.0
    ports:
      - 3000:3000
    # depends_on:
      # "postgres":
      #   condition: service_healthy
      # "subquery-node":
      #   condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=avail-indexer
      - --playground
      - --indexer=http://subquery-node:3000
      - --subscription
      - --unsafe
      - --query-timeout=30000
      - --query-limit=500
